# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# DATASOURCE (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/flood_rescue?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# CONNECTION POOL (Hikari - default)
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000

# JWT
app.jwt.secret=f9e8c4b2a1d7e6f5g4h3i2j1k9l8m7n6p5q4r3s2t1u
app.jwt.expiration-ms=86400000

# ===============================
# SEED DATA (DEV)
# ===============================
app.seed.enabled=true
app.seed.coordinator.email=conchimcu@gmail.com
app.seed.coordinator.phone=0900000002
app.seed.coordinator.password=Anhtu2003
app.seed.coordinator.full-name=\u0110i\u1EC1u ph\u1ED1i vi\u00EAn m\u1EB7c \u0111\u1ECBnh

# ===============================
# UPLOAD
# ===============================
app.upload.rescue-dir=uploads/rescue
# Expose local uploads directory under /uploads/**
spring.web.resources.static-locations=classpath:/static/,file:uploads/

#size picture
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
